### PR TITLE
dark mode implemented

### PR DESCRIPTION
**Pull request by Sabbirfeni**
I have implemented the dark mode feature. Please check out the project.

### CODE REVIEW

**Comment by Sabbirfeni** [comment]
Hey I check this out please.

**Comment by abneribeiro** [comment]
"I liked it; it looks interesting. Good job! However, when dark mode is active, there's a section before the footer that remains white. Did you notice this bug?"

**Comment by Sabbirfeni** [comment]
> I liked it; it looks interesting. Good job! However, when dark mode is active, there's a section before the footer that remains white. Did you notice this bug?

Yes I did

**Comment by Sabbirfeni** [comment]
I tried to figure out but failed. I have another project to do. So I ignored this issue as the main has been completed. But I will try to fix it in near future if possible.

**Pull request merged**
